### ISSUE TITLE
python get_data/download-and-convert-cifar-10.py fails while converting data

### ISSUE THREAD

**Issue by gonzalorodrigo** [NERSC/cori-tf-distributed-examples#1]
Might be a discrepancy between the sklearn version required to run the script and the one loaded by "module load deeplearning"

*System:* Cori

*Commit* e69aef1650c695a4069c61bf9d0bd2084cce11a1

*Commands run:*

mode load deeplearning

python get_data/download-and-convert-cifar-10.py

*Output:*
Downloading...
--2017-07-06 11:08:30--  http://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz
Resolving www.cs.toronto.edu (www.cs.toronto.edu)... 128.100.3.30
Connecting to www.cs.toronto.edu (www.cs.toronto.edu)|128.100.3.30|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 170498071 (163M) [application/x-gzip]
Saving to: 'cifar-10-python.tar.gz'

100%[==============================================================>] 170,498,071 7.34MB/s   in 25s    

2017-07-06 11:08:55 (6.54 MB/s) - 'cifar-10-python.tar.gz' saved [170498071/170498071]

Downloading done.

Extracting...
cifar-10-batches-py/
cifar-10-batches-py/data_batch_4
cifar-10-batches-py/readme.html
cifar-10-batches-py/test_batch
cifar-10-batches-py/data_batch_3
cifar-10-batches-py/batches.meta
cifar-10-batches-py/data_batch_2
cifar-10-batches-py/data_batch_5
cifar-10-batches-py/data_batch_1
Extracting successfully done to /global/u1/g/gprodri/SciSearch/mltools/cifar-10-batches-py.
Converting...
Traceback (most recent call last):
  File "get_data/download-and-convert-cifar-10.py", line 71, in <module>
    ["data_batch_{}".format(i) for i in range(1, 6)]
  File "get_data/download-and-convert-cifar-10.py", line 67, in load_data
    data, labels = shuffle_data(data, labels)
  File "get_data/download-and-convert-cifar-10.py", line 48, in shuffle_data
    data, _, labels, _ = sklearn.cross_validation.train_test_split(
AttributeError: 'module' object has no attribute 'cross_validation'

**Comment by gonzalorodrigo** [comment]
Added A PR in the bitbucket site
